### PR TITLE
Add parsers tests using py.test

### PR DESCRIPTION
**Pull request by redapple**
This PR adds a few tests on the 4 parsers for artists, labels, masters and releases.

The "head50" samples are simple `zcat  discogs_20170401_{artists,labels,releases,masters}.xml.gz | head -n50` calls, so they do not contain 50 entities of each group, but I believe it can help quicly check if the parsing works or not.

This does not test exporters.

The releases parser has a bug on subtracks. I don't know if this issue is already known or not: it looks like only the last subtrack of a track is considered.

### CODE REVIEW

**Comment by redapple** [comment]
@philipmat , I believe this is a good enough first step for better CI.
What do you think?

**Comment by philipmat** [comment]
Looks great! Thank you. Is this dependent on code-cleanup PR?

**Comment by redapple** [comment]
It's independent. Right off the current "master" branch.

**Comment by philipmat** [comment]
As an improvement for the future, would you consider extracting the XML fragments to files in a separate folder? That was we can, one day perhaps, write a tool that fetches the XMLs and extracts a (specific? latest?) node and updates the test files.

I guess it'd be a clumsy way to ensure the discogs folks don't change the structure without us being aware.

**Comment by redapple** [comment]
sorry @philipmat , I do not understand your question. Can you elaborate?

**Comment by philipmat** [comment]
Right now (thanks to you!) we have the XML nodes (eg `artist`) stored inside the `.py` files:

```python
class TestArtistParser(object):

    def test_basic_unicode(self):
        parser = xml.sax.make_parser()
        exporter = AppendingExporter()
        entityHandler = ArtistHandler(exporter)
        parser.setContentHandler(entityHandler)
        parser.parse(BytesIO(b'''<artists>
  <artist>
    <images>
...
```

If we were to store that XML outside the test class, in a say `test-artists.xml`, at one point in the future we could write a cron job that fetches the latest Discogs file, replaces the `test-artists.xml` with an updated version (I have some questions here about the update strategy, but let's *wave hands*), and thus ensures the tests are still passing.

Does that make sense?

**Comment by redapple** [comment]
Ah, I see.
Yes, I thought about having XML snippet and some expected outcome (maybe some pickled object) to make it easier to maintain.
But in the end, I went for a crude way for now. And I'm sure the community will have good ideas for this :)

**Comment by philipmat** [comment]
No, it's great! I don't want to come across as ungrateful - I certainly am thankful for you improving the quality.

I was merely suggesting/making a note of an improvement that could put us on a path of being able to, one day, guard against Discogs schema changes.

**Pull request merged**
