### PR TITLE
PY3 compatibility

### PR DESCRIPTION
**Pull request by pfouque**
Essentially replacing "print" functions, to make it compatible with python 3.

PS : Sorry my IDE is configured to drop trailing spaces and tabs ;)

### CODE REVIEW

**Comment by pfouque** [comment]
The inevitable happened : 

```
  File "/home/travis/build/blitzr/discogs-xml2db/discogsreleaseparser.py", line 216
    teaj.artist_id = self.buffer
                               ^
TabError: inconsistent use of tabs and spaces in indentation.
```

**Comment by philipmat** [comment]
I don't see the `from __future__ import print_function` in the file. Did you test it against 2.7 to make sure it still works?

**Comment by pfouque** [comment]
yes

**Comment by philipmat** [comment]
Ah, thank you for that bit! I had no idea it was optional

**Pull request merged**
