### PR TITLE
remove _images PostgreSQL tables

### PR DESCRIPTION
**Pull request by mche**
Hi!

### CODE REVIEW

**Comment by philipmat** [comment]
Thank you!

**Comment by mche** [comment]
have a nice!

**Comment by ijabz** [comment]
Sorry I don't understand this change, isn't it preventing images fro being added to the database or have I misunderstoood it ?

**Comment by mche** [comment]
There are no img urls on discogs xml now so none DB tables )

**Comment by ijabz** [comment]
Oh yes of course, my bad !

**Comment by ijabz** [comment]
Oh no not my bad at all, we already modify tablles because urls have not been in xml for a while, however the type, width and height are stored and in use this information. Basically it tells me in advance if Disocgs has (any) images of sufficient quality to warrant making a request.

Philip please revert this pull request.

e.g
ubuntu@ip-172-31-39-147:~/code/discogs-xml2db$ head -2 discogs_20170201_artists.xml
<artists>
<artist><images>**<image height="450" type="secondary" uri="" uri150="" width="600"/></images>**<id>1</id><name>The Persuader</name><realname>Jesper Dahlbäck</realname><profile></profile><data_quality>Correct</data_quality><namevariations><name>Persuader</name><name>The Presuader</name></namevariations><aliases><name>Dick Track</name><name>Faxid</name><name>Groove Machine</name><name>Janne Me' Amazonen</name><name>Jesper Dahlbäck</name><name>Lenk</name><name>The Pinguin Man</name></aliases></artist>
ubuntu@ip-172-31-39-147:~/code/discogs-xml2db$

**Comment by philipmat** [comment]
Ugh, looks like it cannot be reverted automatically. I'll revert it by hand.

**Comment by philipmat** [comment]
@ijabz - could you please test and see if it works?

**Pull request merged**
